### ISSUE TITLE
Bech32 & segwit address support?

### ISSUE THREAD

**Issue by afk11** [petertodd/python-bitcoinlib#147]
I've been reviewing for common libraries that may not yet have segwit address support. I haven't seen anyone work on it yet, please add this soon!

https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki

**Comment by petertodd** [comment]
Yup!

Pretty busy right now though, so it'll take some time unless someone else writes that code. Also, I'm not sure that bech32 is 100% stabilized - I'd be more confident on saying it was once it's added to Bitcoin Core. Dunno what's the status of that right now.

**Comment by tsusanka** [comment]
There is a Python implementation by sipa [here](https://github.com/sipa/bech32/tree/master/ref/python)

**Comment by dgpv** [comment]
https://github.com/petertodd/python-bitcoinlib/pull/189

**Comment by ysangkok** [comment]
@dgpv Can this be closed?

**Comment by dgpv** [comment]
@ysangkok I think your comments contain very little signal.

**Comment by afk11** [comment]
@ysangkok looks like it can, thanks for the ping!

**Comment by dgpv** [comment]
In case my (promptly deleted) comment on github reached you, I
apologise.

I commented that "I think your comments contain very little signal"
because it seemed to me at the time that someone tries to do a lot of
low-effort "participation" in the bitcoin-related issues with some
unclear goal.

I see that I was mistaken, and there is genuine effort, that can only
be encouraged.

Please excuse me for the hastly-made comment.
