### ISSUE TITLE
Non-deterministic private key when entropy is too long 

### ISSUE THREAD

**Issue by pedr0-fr** [petertodd/python-bitcoinlib#239]
This scripts prints a different public key every time I run it...
```
from bitcoin.wallet import CBitcoinSecret
key = CBitcoinSecret.from_secret_bytes(b'SOME_RANDOM_SECRET')
print(str(key.pub.hex()))
```

If I replace `b'SOME_RANDOM_SECRET` by `b'SOME_RANDOM'` this doesn't happen... I guess you will probably say it's the user's fault for putting such a long secret but why not raise an exception or do a sha256 if too long for backward compatility

**Comment by mcelrath** [comment]
This seems to be caused by your secret key being too *short*, and the padding being non-deterministic:
```
k._cec_key.get_raw_privkey()                                                                                                                       
b'SOME_RANDOM_SECRET\x00y\x0069d4e4f\x00\x00\x00\x00'
```
Several runs produce different bytes after `b'SOME_RANDOM_SECRET'`. The problem seems to come from the openssl wrapper here: https://github.com/petertodd/python-bitcoinlib/blob/master/bitcoin/core/key.py#L265 which ultimately passes a `void*` to the C openssl code, and grabs python garbage after the end of the string.

This is definitely a bug. We should be:
1. Throwing an exception noting that the input entropy is too short
2. Properly pad the secret value as a 32-byte bignum that openssl expects.

There are additionally endianness issues here, as a big endian secret value and little endian secret value are different private keys. The correct thing to do I think is left-pad with zeroes when represented as big endian (this quantity is supposed to be an integer mod p). The very, very simple solution is to change line 265 of key.py to be:
```
        priv_key = _ssl.BN_bin2bn(secret, len(secret), None)
```
instead of the fixed length 32 which is obviously incorrect for your example. This seems to work for me. @pedr0-fr can you verify?

**Comment by dgpv** [comment]
My opinion (and what is done in python-bitcointx) is that users should do padding themselves. Secret data that has length not equal to 32 should cause exception.

**Comment by dgpv** [comment]
Motivation: enforcing correctness of the code. Unintended padding might be caused by bugs in user code. If the padding is intended, it should be done explicitly.
