### ISSUE TITLE
Please Fix Readme

### ISSUE THREAD

**Issue by eahefnawy** [petertodd/python-bitcoinlib#64]
This may be only my humble opinion, but I really don't understand the github trend of having the README unstyled purely as text and not in markdown. Is that suppose to be cool? It makes it much harder to read and comprehend. Markdown was "invented" for a reason!

Please keep it as it should be, it'd make it much easier for us to use your awesome library.

Thanks for your efforts :)

**Comment by welshjf** [comment]
FYI, you're coming across as a bit insulting. This is not some evil conspiracy to return to the days of monochrome displays. If you look at the history, the README started out as a text file in a simpler project and gained structure over time.

I have no trouble reading or comprehending it, but still agree some formatting would be a positive thing for first impressions. I would go for ReStructured Text over Markdown though, as PyPI only supports RST at present. For consistency, we'd want to convert release-notes.md too; looks like it parses fine as RST already. I'll work on it if @petertodd is on board.

**Comment by eahefnawy** [comment]
I'm sorry if it sounded "insulting" @welshjf, it's just that we look at enough code during our lifetime, we don't have to decode documentations too.

**Comment by welshjf** [comment]
No harm done (though I'm just a passer-by here). I think we all need to remember sometimes to be mindful of how we express our frustrations, especially when our goal is to get others to contribute volunteer work :)

Note related PRs: #24, #68

**Comment by posita** [comment]
@eahefnawy, if you don't see what you like in the existing PRs, you can always submit a new one to effect the very result you desire. @petertodd is very busy guy, but he's usually pretty good about (eventually) merging worthwhile contributions. :+1:

FWIW, submitting actual fixes to documentation of open source projects (especially those in the bitcoin space) is usually very much appreciated by maintainers, since it often gets lost in the shuffle.

Please also consider editing the title of this issue to more accurately describe the problem. From <https://musescore.org/en/developers-handbook/how-write-good-bug-report-step-step-instructions#Title> (**emphasis** added):

> The title should describe the problem as best as possible. **Remember that the title is read more often than any other part of the bug report.**
> 
> *Poor title*: Notes don't display correctly
> This title is not specific enough for someone to look at it a month from now, and remember what the bug report is referring to.
> 
> *Good title*: Stems too short for 32nd and 64th notes
> This title is an improvement over the previous title, because it specifies the type of notes that are affected and identifies the display problem.
> 
> After submitting the issue, it is possible to improve the title.

From <http://university.utest.com/writing-quality-bug-reports-and-utest-etiquette/> (**emphasis** added):

> The title is the face of your report. **It’s the first thing anyone sees and it’s importance cannot be overstated. A good title helps reduce duplicate issues and can quickly convey a summary of the bug.**
> 
> It’s best to avoid generic problems in the title. For example, these should never be used:
> 
> * XYX is not working properly
> * Issue with XYZ
> * XYZ is corrupted/does not look right
> 
> The above example titles add little value in describing the problem. By nature, every report is describing something that is not working as it should. Be specific about what makes it “not working.”
> 
> *Instead of*: Sorting is not working properly.
> 
> *Try*: Sorting is happening in reverse order.
> 
> *Instead of*: Issues with GUI on navigation bar.
> 
> *Try*: Navigation bar is wrapping to a second line.
> 
> Often times, bugs are migrated into the developer’s database that may contain hundreds, if not thousands, of other issues. Imagine trying to search this database for “navigation bar”. That search will return every issue related to the navigation bar. Searching for “wrapping to second line” is much more specific making it easier to find the bug. Your bug report needs to survive (and be useful) beyond the current test cycle; a strong title will help it through it’s journey.

See also <https://university.utest.com/bug-title-recommendations-from-lead-testers/>.

The easier you make it for others to help you, the more likely you'll get what you want.

I hope this helps!
